import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; 
import { Providers } from "./Provider";
import Navbar from "@/components/navbar/Navbar";
import FormCard from "@/components/formCard/FormCard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  const theme = localStorage.getItem('theme');
                  // Default to light theme if no theme is set
                  if (!theme || theme === 'null' || theme === 'undefined') {
                    localStorage.setItem('theme', '"light"');
                    document.documentElement.classList.remove('dark');
                  } else {
                    // Only add dark class if theme is explicitly dark
                    const isDark = theme === '"dark"' || theme === 'dark';
                    if (isDark) {
                      document.documentElement.classList.add('dark');
                    } else {
                      document.documentElement.classList.remove('dark');
                    }
                  }
                } catch (e) {
                  // On error, default to light
                  document.documentElement.classList.remove('dark');
                }
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >   
        <Providers>
          {children}</Providers>
      </body>
    </html>
  );
}
